name: spdn_mobile
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.6
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  jwt_decoder: ^2.0.1  # Add this line
  shared_preferences: ^2.0.15
  image_picker: ^1.1.2
  intl: ^0.17.0  # Add this line
  flutter_plugin_android_lifecycle: ^2.0.27  # Update to the latest version
  image: ^4.0.17
  url_launcher: ^6.2.1
  app_links: ^3.4.5
  pointycastle: ^3.7.3
  crypto: ^3.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Downgraded version to match the SDK

flutter:
  uses-material-design: true
